### ISSUE TITLE
Delete model with fatal

### ISSUE THREAD

**Issue by throrin19** [FiguredLimited/vue-mc#41] opened 2018-03-28 08:31 UTC
Hi, I have a problem with vue-mc :

I try to remove an item on unexist route (I test my interface first). But, if the `model.delete()` failed, the `deleting` is already set to true and I can't retry without refresh my entire collection.

In a normal way, after the request, if it was an error, we can retry the delete. It's possible to fix that ?

Thanks

**Comment by rtheunissen** [comment] 2018-03-28 09:28
Deleting _should_ be set to false when the request has failed. Are you finding that `deleting` is true in the handler? I'll take a look and let you know what I find.

**Comment by throrin19** [comment] 2018-03-28 09:31
I test that with :

```javascript
myModel.delete()
    .then(() => {
        // success case
    })
    .catch((err) => {
        console.log(myModel.deleting); // return true
    });
```

I have to manually set `deleting` to false in the catch case

**Comment by rtheunissen** [comment] 2018-03-28 09:43
That's definitely a bug. 👍

**Comment by rtheunissen** [comment] 2018-04-12 08:08
There's a test called `should set deleting to false on delete failure` which passes. 🤔

**Comment by rtheunissen** [comment] 2018-10-08 23:35
What is the status here?

**Comment by rtheunissen** [comment] 2018-10-18 17:35
@throrin19 I'm going to close this because that test implies that this is not a bug.

**Closed by rtheunissen** 2018-10-18 17:35 UTC
Labels: Waiting
